version: '2'
services:
    localmarketplace-app:
        image: localmarketplace
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://localmarketplace-mysql:3306/localmarketplace?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    localmarketplace-mysql:
        extends:
            file: mysql.yml
            service: localmarketplace-mysql
